# Generated by Django 3.1.2 on 2020-10-04 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
