# Generated by Django 3.1.2 on 2020-10-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_photo_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='alamy_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='fine_art_america_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
