# Generated by Django 3.1.2 on 2020-10-18 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20201007_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='alt_text',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
