# Generated by Django 3.1.2 on 2020-10-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20201018_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='category',
            field=models.CharField(blank=True, choices=[('Animals', 'Animals'), ('Arthropods', 'Arthropods'), ('Autumn', 'Autumn'), ('Architecture', 'Buildings and Architecture'), ('Butterflies', 'Butterflies'), ('Landscapes', 'Landscapes and Nature'), ('Other', 'Other'), ('Pets', 'Pets'), ('Plants', 'Plants and Flowers'), ('Spring', 'Spring'), ('Sunsets', 'Sunsets'), ('Weather', 'Weather'), ('Winter', 'Winter')], default='', max_length=100),
        ),
    ]
