# Generated by Django 3.1.2 on 2020-10-22 18:53

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_photo_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=backend.models.Photo.generate_filename),
        ),
    ]
