# Generated by Django 3.1.2 on 2020-12-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20201022_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='category',
            field=models.CharField(blank=True, choices=[('Animals', 'Animals'), ('Architecture', 'Architecture'), ('Arthropods', 'Arthropods'), ('Autumn', 'Autumn'), ('Butterflies', 'Butterflies'), ('Caterpillars', 'Caterpillars'), ('Landscapes', 'Landscapes'), ('Nature', 'Nature'), ('Night', 'Night Sky'), ('Other', 'Other'), ('Pets', 'Pets'), ('Plants', 'Plants and Flowers'), ('Spring', 'Spring'), ('Sunsets', 'Sunsets'), ('Weather', 'Weather'), ('Winter', 'Winter')], default='', max_length=100),
        ),
    ]
