# Generated by Django 3.1.2 on 2020-12-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20201220_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
