# Generated by Django 3.1.2 on 2021-04-12 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_photo_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='s3_image_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='category',
            field=models.CharField(blank=True, choices=[('Animals', 'Animals'), ('Architecture', 'Architecture'), ('Arthropods', 'Arthropods'), ('Autumn', 'Autumn'), ('Butterflies', 'Butterflies'), ('Caterpillars', 'Caterpillars'), ('Landscapes', 'Landscapes'), ('Pets', 'Pets'), ('Plants', 'Plants and Flowers'), ('Spring', 'Spring'), ('Sunsets', 'Sunsets and Skies'), ('Water', 'Water'), ('Weather', 'Weather'), ('Winter', 'Winter')], default='', max_length=100),
        ),
    ]
