# Generated by Django 3.1.2 on 2021-06-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20210412_0155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('animals', 'Animals'), ('architecture', 'Architecture'), ('arthropods', 'Arthropods'), ('autumn', 'Autumn'), ('butterflies', 'Butterflies'), ('caterpillars', 'Caterpillars'), ('landscapes', 'Landscapes'), ('pets', 'Pets'), ('plants-and-flowers', 'Plants and Flowers'), ('spring', 'Spring'), ('sunsets-and-skies', 'Sunsets and Skies'), ('water', 'Water'), ('weather', 'Weather'), ('winter', 'Winter')], max_length=100)),
                ('slug', models.CharField(blank=True, max_length=100)),
                ('category_image', models.URLField()),
                ('category_image_alt', models.CharField(max_length=100)),
            ],
        ),
    ]
