# Generated by Django 3.1.2 on 2021-06-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_auto_20210630_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('Animals', 'Animals'), ('Architecture', 'Architecture'), ('Arthropods', 'Arthropods'), ('Autumn', 'Autumn'), ('Butterflies', 'Butterflies'), ('Caterpillars', 'Caterpillars'), ('Landscapes', 'Landscapes'), ('Pets', 'Pets'), ('Plants and Flowers', 'Plants and Flowers'), ('Spring', 'Spring'), ('Sunsets and Skies', 'Sunsets and Skies'), ('Water', 'Water'), ('Weather', 'Weather'), ('Winter', 'Winter')], max_length=100),
        ),
    ]
