# Generated by Django 3.1.2 on 2021-07-05 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_auto_20210705_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('Animals', 'Animals'), ('Architecture', 'Architecture'), ('Insects and Spiders', 'Insects and Spiders'), ('Nature', 'Nature'), ('Meteorology', 'Meteorology'), ('Plants and Flowers', 'Plants and Flowers'), ('Seasons', 'Seasons')], max_length=100),
        ),
    ]
